version: '2'

services:
  database:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    env_file:
      - env/database.env

  authoritative:
    build: .
    image: powerdns:latest
    container_name: powerdns
    links:
      - database:db
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081"
    entrypoint: /start.sh
    env_file:
      - env/database.env

  pdnsadmin:
    image: pdnsadmin/pdnsadmin:latest
    container_name: pdnsadmin
    links:
      - database:db
      - authoritative:powerdns
    ports:
      - "8088:80"
    env_file:
      - env/database.env
